// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduBa235737YVFU3WDLwgBpIg7xyEkh0g',
    appId: '1:693101970435:web:d526d159f2849bec31fa36',
    messagingSenderId: '693101970435',
    projectId: 'substation-12f1a',
    authDomain: 'substation-12f1a.firebaseapp.com',
    storageBucket: 'substation-12f1a.firebasestorage.app',
    measurementId: 'G-W1GZJFTDT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIJ1eZMuSM8DGdSeoiuUHL56995sSlwQ',
    appId: '1:693101970435:android:f8c18e7d56812f9631fa36',
    messagingSenderId: '693101970435',
    projectId: 'substation-12f1a',
    storageBucket: 'substation-12f1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0uCNyERty1ErpbiZE85cjMqyf57TZgWw',
    appId: '1:693101970435:ios:35b9ef27abab95ac31fa36',
    messagingSenderId: '693101970435',
    projectId: 'substation-12f1a',
    storageBucket: 'substation-12f1a.firebasestorage.app',
    iosClientId: '693101970435-dujdm1ofom7lp3n6hjc33pq66u71mbm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.substation',
  );
}
